.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "IMG\-GET" "1" "April 2023" ""
.SH "NAME"
\fBimg\-get\fR \- like wget but for many images at once
.SH "SYNOPSIS"
\fBfileporter [\-h] [\-v] root\fR
.SH "DESCRIPTION"
automatically download many images at once\.
.SH "OPTIONS"
.TP
url
the starting which should be scraped
.TP
\-h, \-\-help
show the help message and exit
.TP
\-v, \-\-version
show program's version number and exit
.SH "EXAMPLES"
.nf
$ img\-get "https://raw\.githubusercontent\.com/PlayerG9/img\-get/example/001\.png"
.fi
.SH "AUTHOR"
PlayerG9 \- https://github\.com/PlayerG9/
.SH "COPYRIGHT"
Copyright \(co 2023 PlayerG9\.
.SH "SEE ALSO"
.SS "Repository"
https://github\.com/PlayerG9/img\-get
