#!/usr/bin/env bash

# add executable to path and adding manpage (path_element/man)
#   "If  there  is  no  MANPATH_MAP  line in the configuration file for a given path_element, then it adds all of
#   path_element/../man, path_element/man, path_element/../share/man, and path_element/share/man that  exist  as
#   directories to the search path."
export PATH="${PATH}:$(realpath "$(dirname "${BASH_SOURCE[0]}")/path")"


# autocompletion
complete -W "https:// --help --version" img
