name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - run: scripts/make-archive
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "build/img-get"
        bodyFile: "CHANGELOG.md"
